### ISSUE TITLE
💡 [FEAT] Effort unit

### ISSUE THREAD

**Issue by FelixKratz** [kraanzu/dooit#137]
I would like to add a time unit to efforts. Some todos I would like to quantify the effort in terms of hours and some in terms of work days.
So for example:
Task 1, Effort: 2d
Task 2, Effort: 1h

I am looking forward to the next version, you seem to have made great improvements to the app and it already is the best todo tui imo :)

**Comment by kraanzu** [comment]
Hey, I'm not sure if this is great because everyone has a different idea of `effort` 
It can be anything, I set it to a number to make it sortable!

An alternative to your idea is to use tags!
In the next version, tags are not a separate entity but are built-in within the description itself
For example, if you write a description like this
```
Complete Chapter 7 @finals @3d
```

Then all words starting with `@`  will be highlighted and you can search for them!

**Comment by FelixKratz** [comment]
Ok, sounds good, I will close this then.
