### ISSUE TITLE
💡 [FEAT]

### ISSUE THREAD

**Issue by Arqamz** [kraanzu/dooit#180]
**Is your feature request related to a problem? 😢 Please describe.** 
No, just a suggestion. (Loveeeeeee dooit btw, you rock!)

**Describe the solution you'd like**   🤔
Could you make the default config file that the program uses be visible to us, instead of a new user having nothing to go off of in a blank file maybe they could see the config file both as guidance and being able to _actually_ tweak everything?

**Additional context** 📝
Something declarative like how there's configuration.nix or hyprland.conf

**Comment by kraanzu** [comment]
>  No, just a suggestion. (Loveeeeeee dooit btw, you rock!)

Thanks a lot man! Even though development has been very slow due to other stuff in my personal life. I'm picking up development on this project again :)

> Describe the solution you'd like 🤔
Could you make the default config file that the program uses be visible to us, instead of a new user having nothing to go off of in a blank file maybe they could see the config file both as guidance and being able to actually tweak everything?

Actually yes, there's a default config file but I guess that's not very apparent now, is it?

https://github.com/kraanzu/dooit/blob/main/dooit/utils/default_config.py

I'm working on it and the new config will be much much better. This seems like a hot mess right now

**Comment by Arqamz** [comment]
i should've looked around harder lol.

> I'm working on it and the new config will be much much better. This seems like a hot mess right now

Cant wait!

**Comment by kraanzu** [comment]
I'd add a command to create default config next time :)
