### ISSUE TITLE
💡 [more nesting, enter as escape]

### ISSUE THREAD

**Issue by RannyBergamotte** [kraanzu/dooit#58]
Currently working on a large project, where i wanted to be able to have more nesting within tasks. 

Just allowing for more nesting of tasks and topics would be nice.

Also would be nice if enter key could also act with same functionality as escape key, as when finishing writing/editing a task, it feels natural and would make sense to complete writing with enter too and it feels natural. Also same with selecting and entering a topic.

Love dooit, it's beautifully simple and effective!

**Comment by kraanzu** [comment]
> Just allowing for more nesting of tasks and topics would be nice.

Nesting can be done but It chose not to do it because:
- It would mess up the UI
- It caused a lot of complications while writing code 

> would be nice if enter key could also act with same functionality as escape key

Yes, I was thinking the same 
I'll push an update later to change that in the config file

The main idea behind `escape` to act more like vim \
 but I guess I should re-map `escape` to something like: Cancel the current todo edit?

**Comment by kraanzu** [comment]
Implemented!
